name: abs_wear
description: AudioBookShelf on your watch!
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  archive: ^3.1.2
  bloc: ^8.1.2
  device_info_plus: ^9.1.2
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.4
  http: 1.1.0
  intl: ^0.18.0
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11
  path_provider: ^2.1.2
  rotary_scrollbar: ^0.1.1
  shared_preferences: ^2.2.2
  text_scroll: ^0.2.0 
  volume_controller: ^2.0.7
  wearable_rotary: ^2.0.0

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/static/ABSWear.png"
  

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/static/ABSWear.png
    - assets/static/ABSWear_round.png
    - assets/static/ABSWear_round.svg
