name: Build Flutter APK's and App bundle

on:
  workflow_dispatch:
    inputs:
      build_name:
        description: 'Build Name'
        required: true
        default: '1.0.0'
      build_number:
        description: 'Build Number'
        required: true
        default: '1'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
      SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter doctor -v
      
      - name: Checkout and get packages
        uses: actions/checkout@v4
      - run: flutter pub get

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'android_keystore.jks'
          fileDir: '/home/runner/work/abs_wear/abs_wear/android/app/keystore/'
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Create key.properties file
        run: echo "storePassword=$SIGNING_STORE_PASSWORD" > /home/runner/work/abs_wear/abs_wear/android/key.properties && echo "keyPassword=$SIGNING_KEY_PASSWORD" >> /home/runner/work/abs_wear/abs_wear/android/key.properties && echo "keyAlias=$SIGNING_KEY_ALIAS" >> /home/runner/work/abs_wear/abs_wear/android/key.properties && echo "storeFile=keystore/android_keystore.jks" >> /home/runner/work/abs_wear/abs_wear/android/key.properties

      - name: Build APK
        run: flutter build apk --split-per-abi --release --build-number ${{ github.event.inputs.build_number }} --build-name ${{ github.event.inputs.build_name }} --target "lib/main_production.dart" --flavor production
        env:
          ANDROID_KEYSTORE_PATH: "/home/runner/work/abs_wear/abs_wear/android/app/keystore/android_keystore.jks"
          ANDROID_KEYSTORE_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Build APP BUNDLE
        run: flutter build appbundle --build-number ${{ github.event.inputs.build_number }} --build-name ${{ github.event.inputs.build_name }} --target "lib/main_production.dart" --flavor production
        env:
          ANDROID_KEYSTORE_PATH: "/home/runner/work/abs_wear/abs_wear/android/app/keystore/android_keystore.jks"
          ANDROID_KEYSTORE_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "build/app/outputs/flutter-apk/release/*.apk, build/app/outputs/bundle/productionRelease/*.aab"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: release-apk
          path: build/app/outputs/apk/